# Generated by Django 3.1.12 on 2021-06-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kimetsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('1', '女'), ('0', '男')], max_length=2)),
                ('feutures', models.CharField(max_length=20)),
            ],
        ),
    ]
