# Generated by Django 3.1.12 on 2021-06-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kimetsu',
            name='gender',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=2),
        ),
        migrations.AlterModelTable(
            name='kimetsu',
            table='post',
        ),
    ]
