# Generated by Django 3.1.12 on 2021-06-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210620_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kimetsu',
            old_name='feutures',
            new_name='features',
        ),
    ]
