# Generated by Django 3.1.12 on 2021-06-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210620_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kimetsu',
            name='gender',
            field=models.CharField(choices=[('1', '女'), ('0', '男')], max_length=2),
        ),
    ]
