# Generated by Django 3.1.12 on 2021-06-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20210620_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kimetsu',
            name='gender',
            field=models.CharField(choices=[('女', '女'), ('男', '男')], max_length=2),
        ),
    ]
