# Generated by Django 3.1.12 on 2021-06-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20210620_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kimetsu',
            name='features',
            field=models.CharField(max_length=20, verbose_name='features'),
        ),
        migrations.AlterField(
            model_name='kimetsu',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='kimetsu',
            name='name',
            field=models.CharField(max_length=10, verbose_name='name'),
        ),
    ]
