# Generated by Django 3.1.12 on 2021-06-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20210620_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kimetsu',
            name='features',
            field=models.CharField(max_length=200, verbose_name='features'),
        ),
        migrations.AlterField(
            model_name='kimetsu',
            name='gender',
            field=models.CharField(choices=[('女', '女'), ('男', '男')], max_length=2, verbose_name='gender'),
        ),
    ]
